Milestone 3: Logic branch
Lizdev-05/math-magician pull request #3
Opened 2022-08-03 00:26 UTC by Lizdev-05

In this milestone, I achieved the following...

- I implemented the event handlers needed to use the math logic from calculate.js and operate.js inhe React component.

- I used state and props

- I tested the app in the browser and performed math operations.

2022-08-03 01:07 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @Lizdev-05 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-03 01:07 UTC, tresorsawasawa commented on src/logic/Calculate.js
> +
- [ ] Kindly make sure you fix your eslinterc errors and not disable them in all your files for JavaScript best practices.

2022-08-03 01:07 UTC, tresorsawasawa commented on src/logic/Operate.js
> +
- [ ] As I mentioned in the previous comment,  Kindly make sure you fix your eslinterc errors and not disable them in all your files for JavaScript best practices. If you are using VsCode as IDE, I can suggest you install this extension `Eslint`, after it is installed try to restart your VsCode. Then you will start to see all linters errors when you disable them.

2022-08-03 01:07 UTC, tresorsawasawa commented on src/components/Calculator.js
> +import calculate from '../logic/calculate';
- [ ] As I mentioned in the previous comment, Kindly make sure you fix your eslinterc errors and not disable them in all your files for JavaScript best practices. If you are using VsCode as IDE, I can suggest you install this extension `Eslint`, after it is installed try to restart your VsCode. Then you will start to see all linters errors when you disable them.

2022-08-03 01:07 UTC, tresorsawasawa commented on src/logic/Calculate.js
> +
- [ ] Kindly make sure the files you import to have the correct spelling, as right now your application blocks because of that issue of spelling in different files. for example here is your file is `Operate.js` but you import `operate.js`  that doesn't exist.

2022-08-03 01:07 UTC, tresorsawasawa commented on src/components/Calculator.js
> +import calculate from '../logic/calculate';
- [ ] Here is also the same issue of spelling, make sure you fix it. Your file is `Calculate.js` but you import `calculate.js`  that doesn't exist. And once you fix all your issues, make sure you check your application if is working correctly.

2022-08-03 05:21 UTC, Lizdev-05 commented on src/components/Calculator.js
> +import calculate from '../logic/calculate';
Hello, thank you for the review, I will fix the linter error and I have already changed the name of calculate and operate js respectively, I am not sure why it is not taking effect here, whereas it is already in small letters in my local host.

2022-08-03 08:05 UTC, elyor-doniyorov approved these changes
Hi @Lizdev-05, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ Requested changes are implemented

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-03 08:26 UTC, merged

2022-09-20 21:01 UTC, Lizdev-05 commented on src/logic/Calculate.js
> +
Okay, I will check it out. Thank you

2022-09-20 21:01 UTC, Lizdev-05 commented on src/logic/Operate.js
> +
Okay, I will work on it. Thank you.

2022-09-20 21:02 UTC, Lizdev-05 commented on src/logic/Calculate.js
> +
Thank you for pointing it out. I will work on it.

2022-09-20 21:02 UTC, Lizdev-05 commented
Thanks for reviewing and approving my project, I appreciate it.